name: CMake with GLFW on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            os_name: windows
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            os_name: unix
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            os_name: unix
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Set version number Unix
      if: matrix.os == 'ubuntu-latest'
      id: version-number
      shell: bash
      run: |
        version=$(grep -oP 'project\(.*VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
        echo "version-number=$version" >> "$GITHUB_OUTPUT"

    - name: Set version number Windows
      if: matrix.os == 'windows-latest'
      id: version-number-w
      run: |
        $version = Get-Content CMakeLists.txt -Raw | Select-String -Pattern 'project\(.*VERSION ([0-9]+\.[0-9]+\.[0-9]+)' | ForEach-Object { $_.Matches.Groups[1].Value.Trim() }
        echo "version-number=$version" >> "$GITHUB_OUTPUT"
        echo "$version"
        
    - name: Download GLFW
      run: |
        git clone --branch 3.3.9 --depth 1 --recursive https://github.com/glfw/glfw.git
        mv glfw glfw-3.3.9

      working-directory: ${{ github.workspace }}

    - name: Install libxrandr-dev on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          
    - name: Set up CMake
      if: matrix.os == 'windows-latest'
      run: |
            $url = "https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-windows-x86_64.msi"

            Invoke-WebRequest -Uri $url -OutFile cmake_installer.msi

            Start-Process -Wait -FilePath msiexec -ArgumentList "/i", "cmake_installer.msi", "/quiet", "/qn"
            
    - name: Configure CMake with GLFW
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Create archive Windows
      if: matrix.os == 'windows-latest'
      run: |
            Compress-Archive -Path ./build/ -DestinationPath "RGE-${{ steps.version-number-w.outputs.version-number }}.zip"
            
    - name: Create archive Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
            zip -r "RGE-${{ steps.version-number.outputs.version-number }}.zip" ./build/
            
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ matrix.os }}-${{ matrix.c_compiler }}-${{ steps.version-number.outputs.version-number }}${{ steps.version-number-w.outputs.version-number }}"
          prerelease: true
          title: "Release Build"
          files: RGE.zip

